language: python
python: 3.6
install: 
  - pip install .
  - pip install codecov
  - pip install pytest pytest-cov
script: pytest --verbose -p no:warnings --cov=./
git:
  depth: 1
after_success:
  - codecov