language: python
python: 3.6
install: 
  - pip install .
  - pip install codecov
  - pip install pytest>=3.6 pytest-cov
script: pytest --verbose --cov=./ --cov-report=xml
git:
  depth: 1
after_success:
  - codecov